#**🌈 Numpy(넘파이) : 수치 데이터, 배열 처리를 위한 파이썬 라이브러리**
- 공식사이트 : https://numpy.org/
- 참고문서 : https://numpy.org/doc/
- 명령어 참고 사이트 : https://ebbnflow.tistory.com/160

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_VfYfuw4JGQC0QLtbrhWyAQgW9qD9fXanG34lWGAyI1y34PxtAPagPNkCTAoX7_x7sFw&usqp=CAU)

###**▶ Numpy란?**
- Numerical Python의 줄임말
- 벡터, 행렬, 다차원 배열의 처리를 지원
- 수치 계산을 위해 구현된 기능 제공

<br>

###**▶ 넘파이 배열 (ndarray)**
- 넘파이의 핵심적인 객체는 다차원 배열이다.
- 넘파이는 ndarray(n차원 배열의 약자) 객체를 제공한다. 이때, 차원은 좌표계의 축과 같다.
- <b><u>ndarray 객체는 동일한 자료형의 항목들만 저장할 수 있다.</u></b>

<br>

###**▶ 수학 함수들 (np.xxx)**
- 기본 함수 : abs(절대값), sqrt(제곱근), square(제곱), exp(지수 e), log(로그), log10(밑이 10인 로그), sin, cos, tan
- 통계 함수 : sum(합계), mean(산술평균), std(표준편차), var(분산), max(최대값), min(최소값), median(중간값), argmin(최소값 인덱스), argmax(최대값 인덱스)
- 정렬 함수 : sort(정렬, axis)
- 난수 발생(numpy.random 모듈) : seed(시드 지정), shuffle(임의 섞기), rand(균등분포 추출), randint(최소/최대 중)

- 참고 사이트 : https://sacko.tistory.com/8


#### <b>파이썬 기본 복습</b>

In [ ]:
# 변수 num에 10 저장하기


In [ ]:
# 변수 num 출력하기 (cf. script mode)


10


In [ ]:
# 변수 num 출력하기 (cf. interactive mode)
num

In [ ]:
# 리스트 nlist에 1, 2, 3, 4, 5 저장하고 출력하기
nlist =[1.2.3.4.5]


#### <b>리스트를 이용한 예제</b>

In [ ]:
# 리스트 선언
midterm=[70, 80, 90] # 중간고사 국,영,수 성적
final=[80, 90, 100] # 기말고사 국,영,수 성적

: 

In [ ]:
# 리스트의 모든 원소 5씩 증가시키기
for i in range(3):
    midterm[i] += 5
midterm

[75, 85, 95]

In [ ]:
# 리스트 더하기


[150, 170, 190]

<u>*★파이썬에서 2개의 리스트를 서로 더하면, 2개의 리스트를 연결(concatenate)한 형태가 됨.*</u>

In [ ]:
# 리스트 원소 각각 5씩 증가시키기 (올바른 방법)
result=[]



result

[75, 85, 95]

#### <b>넘파이 사용하기 (기초)</b>
- 넘파이 배열을 만들려면 넘파이가 제공하는 array 함수를 이용한다. 즉, np.array()를 호출하여 생성한다.
- array 함수에 파이썬 리스트를 전달하면 넘파이 배열이 생성된다.
- 넘파이 배열과 스칼라(값)를 연산하면 반복문 없이도 모든 원소에 연산이 적용된다.
- 반복문 없이 넘파이 배열 간 같은 인덱스의 원소끼리 연산을 수행할 수 있다. (벡터화 연산)

---

In [ ]:
# 넘파이 라이브러리 불러오기
import numpy as np

In [ ]:
# 리스트(midterm)를 넘파이 배열(midterm_arr)로 변환하기


array([70, 80, 90])

In [ ]:
# 넘파이 배열 midterm_arr 확인하기


array([140, 160, 180])

In [ ]:
# 배열의 모든 원소 5씩 증가시키기 (스칼라와 덧셈)


array([ 85,  95, 105])

<u>*★넘파이 배열을 이용하면 수학적 연산이 훨씬 편리하다!!!*</u>

---
**응용문제 :** 넘파이 배열 midterm_arr의 모든 원소를 3배하여 넘파이 배열 score에 저장하고 출력해보자.

---

array([210, 240, 270])

---
**응용문제 :** 중간고사와 기말고사의 국, 영, 수 점수를 더하여 넘파이 배열 total에 저장하고 출력해보자.

---

array([150, 170, 190])

#### <b>넘파이 사용하기 (다차원 배열)</b>
<img src='https://drive.google.com/uc?id=1ZGe5JhvFZ_aKlaPkWnrGcFJgABVsMoAw' height=270>

---

**(1) 1차원 배열**

In [ ]:
array1 =
array1

array([1, 2, 3])

In [ ]:
print('array1의 type:',           )
print('array1의 shape:',          )
print('array1의 dimension:',      )

**(2) 2차원 배열**

In [ ]:
array2 =

In [ ]:
print('array2의 type:',           )
print('array2의 shape:',          )
print('array2의 dimension:',      )

**(3) 3차원 배열**

In [ ]:
array3 =

In [ ]:
print('array3의 type:',           )
print('array3의 shape:',          ) # (table, row, col)
print('array3의 dimension:',      )

**(+) 넘파이 배열 더 쉽게 생성하는 법**
* arange() : 특정 범위의 수로 구성된 1차원 배열 생성
* reshape() : 배열의 차원과 크기를 변경

In [ ]:
# 0부터 시작해 3개의 원소로 구성된 배열

arr

array([0, 1, 2])

In [ ]:
# 3 이상 10 미만의 정수로 구성된 배열 (간격 1)
arr =
arr

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3 이상 10 미만의 홀수로 구성된 배열 (간격 2)
arr =
arr

array([3, 5, 7, 9])

In [ ]:
# 0부터 시작해 10개의 원소로 구성된 배열을 2*5 형태로 변환
arr =
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

---
**응용문제 :** 원소가 0부터 시작해 1씩 증가하는 3*3 형태의 넘파이 배열을 만들어보자.

---

In [ ]:
arr =
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### <b>넘파이 사용하기 (활용)</b>

In [ ]:
# 넘파이 배열 midterm_arr 평균 구하기 (국, 영, 수 평균)


80.0

In [ ]:
# 넘파이 배열 midterm_arr 최소값, 최대값 구하기


(70, 90)

In [ ]:
# 넘파이 배열 midterm_arr 합계 구하기 (국, 영, 수 총점)


240

---
####**▶▶▶ 정리**
---
* 넘파이 배열 만들기 np.array(), np.arange()
* 넘파일 배열 차원 확인하기 ndim
* 넘파이 배열 형태 확인하기 shape
* 배열 간 덧셈, 뺄셈, 곱셈, 나눗셈 가능
* 넘파이 함수 : sum, min, max 등
---
*※ 넘파이 배열 슬라이싱 등 넘파이와 관련된 더 복잡한 내용들은 필요할 때마다 또 이야기 하겠습니다.*